title: Dr. Mujawar
name: Dr. Mubarak A. Mujawar
description: Plasma Physics | Atmospheric-Pressure Plasma | Nanomaterials | Sensors | Additive Manufacturing
url: "https://imsmam.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.28.0"

plugins:
  - jekyll-include-cache
  - jekyll-seo-tag

author:
  name: "Mubarak A. Mujawar"
  avatar: "/assets/img/profile.jpg"
  bio: "Assistant Professor of Engineering Physics"

  links:
    - label: "Department of Physical Sciences"
      icon: "fas fa-university"
      url: "https://erau.edu"
    
    - label: "Embry-Riddle Aeronautical University"
      icon: "fas fa-university"
      url: "https://erau.edu"

    - label: "Daytona Beach, FL"
      icon: "fas fa-map-marker-alt"
      url: ""

    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:your-email@erau.edu"

    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/"

    - label: "Scite"
      icon: "fas fa-book"
      url: "https://scite.ai/users/mujawar-jrkVz"


defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

header_pages:
  - research.md
  - publications.md
  - teaching.md
  - cv.md
  - contact.md
