title: Mubarak A. Mujawar
description: Plasma Physics | Atmospheric Pressure Plasma | Nanomaterials | Sensors | Additive Manufacturing

theme: jekyll-theme-minimal

logo: /assets/img/profile.jpg

show_downloads: false
